version: '3.8'
services:
  db:
    image: postgres:15.4-alpine
    restart: always
    environment:
      - POSTGRES_DB=TestDatabase
      - POSTGRES_USER=testUsername
      - POSTGRES_PASSWORD=testPassword
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local